vlog -work work /home/luiz/Documents/projects/ELE1717/processador_4/simulation/modelsim/register_bank.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.register_bank_vlg_vec_tst
onerror {resume}
add wave {register_bank_vlg_vec_tst/i1/clk}
add wave {register_bank_vlg_vec_tst/i1/clr}
add wave {register_bank_vlg_vec_tst/i1/Rp_addr}
add wave {register_bank_vlg_vec_tst/i1/Rp_addr[3]}
add wave {register_bank_vlg_vec_tst/i1/Rp_addr[2]}
add wave {register_bank_vlg_vec_tst/i1/Rp_addr[1]}
add wave {register_bank_vlg_vec_tst/i1/Rp_addr[0]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[15]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[14]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[13]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[12]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[11]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[10]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[9]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[8]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[7]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[6]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[5]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[4]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[3]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[2]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[1]}
add wave {register_bank_vlg_vec_tst/i1/Rp_data[0]}
add wave {register_bank_vlg_vec_tst/i1/Rp_rd}
add wave {register_bank_vlg_vec_tst/i1/Rq_addr}
add wave {register_bank_vlg_vec_tst/i1/Rq_addr[3]}
add wave {register_bank_vlg_vec_tst/i1/Rq_addr[2]}
add wave {register_bank_vlg_vec_tst/i1/Rq_addr[1]}
add wave {register_bank_vlg_vec_tst/i1/Rq_addr[0]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[15]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[14]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[13]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[12]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[11]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[10]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[9]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[8]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[7]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[6]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[5]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[4]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[3]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[2]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[1]}
add wave {register_bank_vlg_vec_tst/i1/Rq_data[0]}
add wave {register_bank_vlg_vec_tst/i1/Rq_rd}
add wave {register_bank_vlg_vec_tst/i1/W_addr}
add wave {register_bank_vlg_vec_tst/i1/W_addr[3]}
add wave {register_bank_vlg_vec_tst/i1/W_addr[2]}
add wave {register_bank_vlg_vec_tst/i1/W_addr[1]}
add wave {register_bank_vlg_vec_tst/i1/W_addr[0]}
add wave {register_bank_vlg_vec_tst/i1/W_data}
add wave {register_bank_vlg_vec_tst/i1/W_data[15]}
add wave {register_bank_vlg_vec_tst/i1/W_data[14]}
add wave {register_bank_vlg_vec_tst/i1/W_data[13]}
add wave {register_bank_vlg_vec_tst/i1/W_data[12]}
add wave {register_bank_vlg_vec_tst/i1/W_data[11]}
add wave {register_bank_vlg_vec_tst/i1/W_data[10]}
add wave {register_bank_vlg_vec_tst/i1/W_data[9]}
add wave {register_bank_vlg_vec_tst/i1/W_data[8]}
add wave {register_bank_vlg_vec_tst/i1/W_data[7]}
add wave {register_bank_vlg_vec_tst/i1/W_data[6]}
add wave {register_bank_vlg_vec_tst/i1/W_data[5]}
add wave {register_bank_vlg_vec_tst/i1/W_data[4]}
add wave {register_bank_vlg_vec_tst/i1/W_data[3]}
add wave {register_bank_vlg_vec_tst/i1/W_data[2]}
add wave {register_bank_vlg_vec_tst/i1/W_data[1]}
add wave {register_bank_vlg_vec_tst/i1/W_data[0]}
add wave {register_bank_vlg_vec_tst/i1/W_wr}
run -all
